import random, os
os.system("cls")
#------------------------------------------------------------------ GLOBAL VAIRABLE -------------------------------------------------------------------------
count= 0
list=[]
sum = 0                                                             #COMPUTER GENERATE RANDOM NUMBER TILL SUM == USER INPUT NUMBER

#------------------------------------------------------------------- MAIN CODE ---------------------------------------------------------------------------------
print("Enter a numberin the Range 1-500".center(70,"-"))
print("")
number = int(input("Enter Number:\t"))                              #USER INPUT
print("")
for i in range(1,1001):
    if(i==1000):                                                    #MAX 1000 STEPS. ONSIDER IT AS AN STACK MEMORY
        print("Maximum Limit Reach.Try Again.".center(60,"-"))
        exit()
    if(sum==number):                                                #REACH THE DESIRE RESULT
        print("\n\nIt took {} Steps to reach number {}".format(count,number))
        for i in list:
            if(i=="+"):
                print("+", end=" ")
            elif(i=="-"):
                print("-", end=" ")
            else:
                print(i, end=" ")
        print("= {}\n".format(sum))
        exit()
    
    rand = random.randint(1,11)                                      #COMPUTER GENERATE SOME RANDOM NUMBER
    print("{} Random number generated is: {}".format(i,rand), end =".  ")
    count += 1                                                       #COUNT HOW MANY RANDOM NUMBER GENERATED BY COMPUTER(STEPS)
    
    if(sum>number):                                                  #MEANS SUM CROSS THE INPUT NUMBER WE HAVE TO GO BACK(SUBSTRACT SOME NUMBER)
        current=sum
        sum -= rand
        list.append("-")                                              #JUST FOR VISUAL REPRESENTATION THAT NOW WE ARE SUBSTRACTING NUMBER
        list.append(rand)                                             #ADD RANDOM NUMBER INTO LIST
        print("Current Sum is {}.  Need SUB of {} from {}.  So Sum become: {}".format(current,rand,current,sum))
        
    else:
        current=sum
        sum += rand                                                  #MEANS SUM LESS THAN INPUT NUMBER WE HAVE ADD THE GENERATED RANDOM NUMBER
        list.append("+")
        list.append(rand)                                             #ADD RANDOM NUMBER INTO LIST
        print("Current Sum is {}.  Need ADD of {} in {}.  So Sum become: {}".format(current,rand,current,sum))
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------